packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': ^1.4.18
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/tanstack-query': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@prisma/client': ^7.2.0
  better-auth: ^1.4.18
  dotenv: ^17.2.2
  typescript: ^5
  zod: ^4.1.13
